6.ログイン機能の実装
yanbaru-expert/team_project_49 pull request #24
Opened 2021-04-18 14:03 UTC by shutheonetokyo

## issue 6

close #6

## 実装内容
・gemを追加
・新規登録・ログイン・ログアウトのリンクを追加
・テスト用ユーザーを作成できるように設定
・全てのページを「ログイン必須」に変更

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-04-19 00:13 UTC, T-Tsujii requested changes

2021-04-19 00:13 UTC, T-Tsujii commented on app/controllers/items_controller.rb
> +  before_action :authenticate_user!
このコントローラはなぜ必要なのでしょうか。
教材に含まれていてもタスクと関係のないことをしないように注意しましょう。

2021-04-20 04:50 UTC, shutheonetokyo commented on app/controllers/items_controller.rb
> +  before_action :authenticate_user!
失礼いたしました。
texts_controller.rbの方ににログイン必須のメソッドを追加しました。
ご確認のほどお願いいたします。

2021-04-20 05:48 UTC, T-Tsujii requested changes

2021-04-20 05:48 UTC, T-Tsujii commented on app/controllers/texts_controller.rb
> +  before_action :authenticate_user!
`before_action :authenticate_user!` は `ApplicationController` に入れましょう。

ログイン前提のアプリで，各コントローラに入れる方式では漏れる可能性があります。

2021-04-20 05:49 UTC, T-Tsujii commented
コンフリクトの解消もお願いします。

2021-04-20 08:53 UTC, shutheonetokyo commented
ApplicationControllerにログイン必須のメソッドを追加、コンフリクトの解消を行いました。
コンフリクトの解消ができているか不安なので、ご確認のほどお願いいたします！
何度も申し訳ありません。

2021-04-20 08:57 UTC, T-Tsujii requested changes

2021-04-20 08:57 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> +
正しくはこの形式ですね。

```suggestion
    <header>
      <% if user_signed_in? %>
        <%= link_to "アカウント編集", edit_user_registration_path %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" } %>
      <% else %>
        <%= link_to "ログイン", new_user_session_path %>
        <%= link_to "新規登録", new_user_registration_path %>
      <% end %>
    </header>
    <main>
      <%# max_width メソッドは application_helper.rb に記載 %>
      <div class="base-container <%= max_width %>">
        <%= yield %>
      </div>
    </main>
    <footer>
    </footer>
```

2021-04-20 08:57 UTC, T-Tsujii commented on config/routes.rb
> +<<<<<<< HEAD
コンフリクトの痕跡が残っていますよ。

2021-04-20 09:45 UTC, shutheonetokyo commented
application.html.erbの内容を修正しました。

また、config/routes.rbにあったコンフリクトの痕跡を消しました。
ケアレスミス失礼しました。

再度ご確認お願いいたします！

2021-04-20 11:48 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-20 14:24 UTC, merged