5. バリデーションを追加(migrateフォルダとmodelフォルダ）,enumを追加
yanbaru-expert/team_project_49 pull request #27
Opened 2021-04-19 18:25 UTC by nuntanunta5153

## issue 5

close #5 

## 実装内容

・マイグレーションファイルにValidationを追加。
・モデルにValidationを追加。

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-04-19 21:28 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-22 13:58 UTC, T-Tsujii requested changes

2021-04-22 13:58 UTC, T-Tsujii commented on db/migrate/20210418040204_create_texts.rb
> +      t.integer :genre, null: false, default: 0
マイグレーションファイルの修正はしないようにしてください。

もしテーブルの制約を変更されたい場合は，新しくマイグレーションファイルを作成して対応して下さい。
（難易度が高いと思われる場合は対応されなくて大丈夫です）

2021-04-22 14:05 UTC, nuntanunta5153 commented on db/migrate/20210418040204_create_texts.rb
> +      t.integer :genre, null: false, default: 0
かしこまりました。次回以降気をつけます！
今現在、ギットのことで頭がいっぱいになり、
整理できない状態になっているので、
今回は対応せずにこのままマージして先に進んでもよろしいでしょうか？

2021-04-23 09:27 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-23 09:28 UTC, merged