日本語ファイル・表示名の設定
yanbaru-expert/team_project_49 pull request #33
Opened 2021-04-22 14:46 UTC by shutheonetokyo

close #14

## 実装内容
- config/locales/ja.yml に各モデル・カラムの日本語訳を設定
- enum-help を追加
- texts, movies テーブルの genre に対応する表示名 config/locales/enums.ja.yml に追加

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-04-22 22:10 UTC, T-Tsujii requested changes

2021-04-22 22:10 UTC, T-Tsujii commented on config/locales/enums.ja.yml
> +    text:
`text` の方に何も入っていないですね。

2021-04-22 22:10 UTC, T-Tsujii commented on config/locales/enums.ja.yml
> +        code_name: "name"
```suggestion
```

2021-04-22 22:11 UTC, T-Tsujii commented
コンフリクトの解消もお願いします

2021-04-23 06:41 UTC, shutheonetokyo commented
textにgenreに対応する指示名を追加しました。
コミット名の入力途中でEnterを押してしまい、コミット名が中途半端になってしまいました。

また、コンフリクトも解消いたしましたので、一通りご確認のほどお願いいたします。

2021-04-23 06:45 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-23 12:39 UTC, merged