管理者画面の実装
yanbaru-expert/team_project_49 pull request #35
Opened 2021-04-29 02:23 UTC by shutheonetokyo

close #18

## 実装内容
- 管理者画面を追加
- db/seeds.rb をタスク6と同様の形式（何度実行してもエラーが出ない形式）に修正
- ユーザー，動画，テキスト教材を管理者画面から追加できるように設定
- 管理者画面以外のスタイルに影響が出ないように対処
- db/seeds.rbの改行を修正

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-04-29 03:24 UTC, T-Tsujii requested changes

2021-04-29 03:24 UTC, T-Tsujii commented on app/admin/users.rb
> +  permit_params :name, :age, :address
この状態ではユーザーの登録ができません。
`app/admin/admin_users.rb` を参考にしてみましょう。

2021-04-29 03:24 UTC, T-Tsujii commented on db/seeds.rb
> +AdminUser.find_or_create_by!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?
この作業が抜けています！

> db/seeds.rb をタスク6と同様の形式（何度実行してもエラーが出ない形式）に修正

2021-04-30 01:29 UTC, T-Tsujii requested changes

2021-04-30 01:29 UTC, T-Tsujii commented on db/seeds.rb
> +PASSWORD_CONFIRMATION = 'password'
定数は上の方に固めるべきですね。 `PASSWORD_CONFIRMATION = 'password'` は使用していないと思います。

2021-04-30 01:29 UTC, T-Tsujii commented on db/seeds.rb
> +AdminUser.find_or_create_by!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') do |admin_user|
`find_or_create_by` の使い方が間違っていますよ。引数に入れるのは，あくまで検索条件です。

```suggestion
AdminUser.find_or_create_by!(email: ADMIN_EMAIL) do |admin_user|
```

2021-04-30 01:29 UTC, T-Tsujii commented on app/admin/users.rb
> +    column :sign_in_count
この2つのカラム は存在しないので削った方がよいですよ。
（admin_userの方もデフォルトでは存在しないですが）

2021-05-01 06:47 UTC, T-Tsujii requested changes

2021-05-01 06:47 UTC, T-Tsujii commented on db/migrate/20210418062749_devise_create_users.rb
> +      t.string :address
今気付きましたが，こちらは今回のアプリと関係がないので削ってください。

```suggestion
```

2021-05-01 06:47 UTC, T-Tsujii commented on db/seeds.rb
> +ADMIN_PASSWORD = 'password'
ここは3行目に移動しましょう。

2021-05-01 11:42 UTC, shutheonetokyo commented on db/migrate/20210418062749_devise_create_users.rb
> +      t.string :address
削除するのを忘れていました。
失礼しました。

2021-05-01 21:59 UTC, T-Tsujii approved these changes
LGTMです！

2021-05-02 05:53 UTC, merged