テキスト教材一覧ページの追加
yanbaru-expert/team_project_49 pull request #36
Opened 2021-04-30 07:38 UTC by nuntanunta5153

【注意】不要な見出し・文言は削除してプルリクを出して下さい

## issue 番号

【備考】「close #issue番号」を記載することで，プルリクがマージされると同時に issue が close されるようになります

（例）
close #1

## 実装内容

原則，マークダウン記法のリストで記載すること

(例)

- リスト1
  - リスト1-1
  - リスト1-2  

## 参考資料（必要があれば）

マークダウン記法のリンクを用いて記載すること

(例)

- ログイン機能
  - [やんばるエキスパートアプリ](https://www.yanbaru-code.com/texts/219)

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考（必要があれば）

2021-04-30 07:51 UTC, T-Tsujii requested changes

2021-04-30 07:51 UTC, T-Tsujii commented on app/controllers/texts_controller.rb
> +    end
これでも一応動作しますが，想定外のジャンルを表示される可能性があるので，ホワイトリストにした方がよいですよ。（例えば `invisible` が表示されてしまいます）

`*****` の箇所は考えてください。
```suggestion
    if params[:genre].in?(*****)
      @texts = Text.where(genre: params[:genre])
    else
      @texts = Text.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"])
    end
```

2021-04-30 07:51 UTC, T-Tsujii commented on app/views/texts/index.html.erb
> +
不要な空行は削りましょう。

2021-04-30 07:51 UTC, T-Tsujii commented on app/views/texts/index.html.erb
> +    <% @texts.each do |text| %>
ここはできれば「コレクション」をレンダリングした方がよいですね。

2021-04-30 07:51 UTC, T-Tsujii commented on app/views/texts/show.html.erb
> +#heading{
スタイルは `app/assets/stylesheets` 内に書きましょう。

その前に，こちらは今回のタスクと関係がないのではありませんか。

2021-04-30 09:24 UTC, nuntanunta5153 commented on app/views/texts/index.html.erb
> +    <% @texts.each do |text| %>
不要な行でした。すみません。

2021-04-30 09:24 UTC, nuntanunta5153 commented on app/views/texts/index.html.erb
> +
削りました。

2021-04-30 09:25 UTC, nuntanunta5153 commented on app/views/texts/show.html.erb
> +#heading{
_collection.html.erbをtextフォルダの中に入れ

`<%= render "texts/collection" %>`

をindex.html.erbに記述しました。

2021-04-30 09:32 UTC, nuntanunta5153 commented on app/controllers/texts_controller.rb
> +    end
自分で調べてみても何を()の中に代入すればいいのかわかりません。（.in?やホワイトリストだったり、やんばるエキスパートの教材でなにか該当する箇所がないか調べました。）

ホワイトリストという単語からストロングパラメーターを使うのかと思ったのですが、今回の課題はユーザーから入力する箇所ではないと思ったので、違うのかな等、そこの部分で悩んでいます。なにかヒントをいただけますでしょうか？

2021-05-01 06:43 UTC, T-Tsujii requested changes

2021-05-01 06:43 UTC, T-Tsujii commented on app/controllers/texts_controller.rb
> +    if params[:genre].in?(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"])
これは反対ですね。
まだリンクがないので確認できないと思いますが，これですと例えばPHPテキスト教材が対応できないですね。

Railsテキスト教材以外のように，各ジャンルでテキスト教材として表示したいジャンルの配列とする必要があります。

2021-05-01 06:43 UTC, T-Tsujii commented on config/routes.rb
> +  resources :texts
ルーティングは必要なものに制限するようにしていきましょう。

```suggestion
  resources :texts, only: [:index, :show]
```

2021-05-01 06:43 UTC, T-Tsujii commented on app/views/texts/index.html.erb
> +    <%= render "texts/collection" %>
肝心の変数を渡し忘れています。最も簡潔に書くなら次の形ですね。

```suggestion
    <%= render @texts %>
```

2021-05-01 12:17 UTC, T-Tsujii requested changes

2021-05-01 12:17 UTC, T-Tsujii commented on app/controllers/texts_controller.rb
> +    end
こちらでもないですね。

この部分はこのタスクと直接関係ないので後回しにしましょうか。リンクがないと理由も分かりづらいと思いますので。

```suggestion
@texts = Text.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"])
```

2021-05-01 13:44 UTC, T-Tsujii requested changes

2021-05-01 13:44 UTC, T-Tsujii commented on app/controllers/texts_controller.rb
> +    @texts = Text.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"])
ジャンルの表記が間違っています！

textモデルの enumの書き方に合わせないといけないです。

2021-05-01 13:44 UTC, T-Tsujii commented on app/views/texts/_collection.html.erb
> +    <% @texts.each do |text| %>
ファイル名は `_text.html.erb` にしなければならないですね。

2021-05-01 14:04 UTC, T-Tsujii approved these changes
LGTMです！

2021-05-01 14:05 UTC, merged