テキスト教材一覧の修正
yanbaru-expert/team_project_49 pull request #39
Opened 2021-05-04 11:15 UTC by nuntanunta5153

## 実装内容

テキスト教材一覧のビューファイルを修正。
カードタイプで表示されるように修正。

## チェックリスト

【補足】プルリクを出した後，クリックしてチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考（必要があれば）

2021-05-04 11:28 UTC, T-Tsujii requested changes

2021-05-04 11:28 UTC, T-Tsujii commented on app/views/texts/index.html.erb
> +    <%= render "texts/text" %>
collectionをレンダリングする方が速度が速くなるので，ここはそのままにしましょう。
`<div class="row">` は繰り返してはいけないのでここですね。

```suggestion
    <div class="row">
      <%= render @texts %>
    </div>
```

2021-05-04 11:28 UTC, T-Tsujii commented on app/views/texts/_text.html.erb
> +</div>
collectionをレンダリングする場合は each が不要になります。

```suggestion
<div class="col-12 col-md-6 col-lg-4">
  <div class="card card-style">
    <a class="text-decoration-none" target="_blank" href="/texts/<%= text.id %>">
      <div class="card-body">
        <img class="card-img-top" src="https://d5izmuz0mcjzz.cloudfront.net/texts/no_image.jpg" alt="Card image cap">
        <p class="card-text"><%= text.title %></p>
        <p class="card-title">【<%= text.genre %>】</p>
      </div>
    </a>
  </div>
</div>
```

2021-05-04 11:28 UTC, T-Tsujii commented on app/views/texts/index.html.erb
>              <input type="text"class='form-control' placeholder="教材を探す">
```
  <div class="row">
    <div class="col-4 text-center offset-4">
      <h2 class="text-title mt-5">Ruby/Rails テキスト教材</h2>
      <input type="text"class='form-control' placeholder="教材を探す">
    </div>
  </div>
```

の箇所がスマホサイズに対応できていません。

ここは `row` や `col-4` を使うのではなく， CSS で `max-width` を設定して対応しましょう。

2021-05-05 23:48 UTC, T-Tsujii requested changes
LGTMです！

2021-05-05 23:49 UTC, nuntanunta5153 commented on app/views/texts/index.html.erb
> +    <%= render "texts/text" %>
ここが`<%= render @texts %>`だとどうしてもローカルでうまく表示されなかったので、
`<%= render "texts/text" %>`で記述しました。

2021-05-05 23:57 UTC, T-Tsujii approved these changes
LGTMです！

2021-05-06 00:00 UTC, merged