Rails動画教材ページの実装
yanbaru-expert/team_project_49 pull request #40
Opened 2021-05-07 14:33 UTC by shutheonetokyo

close #21

## 実装内容
- ルーティング、moviesコントローラー、ビューの作成
- ルーティング、コントローラー、ヘッダーのhtmlファイルの修正
- Ruby/Rails 動画教材の表示
- Ruby/Rails 動画教材の配置の修正

##チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2021-05-07 22:32 UTC, T-Tsujii requested changes

2021-05-07 22:32 UTC, T-Tsujii commented on app/controllers/movies_controller.rb
> +
動画に詳細ページは存在しないのではありませんか。

2021-05-07 22:32 UTC, T-Tsujii requested changes

2021-05-07 22:32 UTC, T-Tsujii commented on config/routes.rb
> +  resources :movies, only: [:index, :show]
```suggestion
  resources :movies, only: :index
```

2021-05-08 06:06 UTC, shutheonetokyo commented
失礼しました。
showアクションを削除いたしました。

また、Rails動画教材で表示するジャンル名が指定されていたものと違っていたので、その箇所も修正いたしました。

再度ご確認のほどお願いいたします！

2021-05-08 06:34 UTC, T-Tsujii approved these changes
LGTMです！
ジャンル名の件失礼しました。

2021-05-08 11:42 UTC, merged