ページ全体の設定を追加
yanbaru-expert/team_project_49 pull request #6
Opened 2021-04-17 02:56 UTC by hirokuni-k

## 3

close #3 

## 実装内容
ページ全体の設定を追加

2021-04-17 12:03 UTC, T-Tsujii requested changes

2021-04-17 12:03 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> +      <#% max_width メソッドは application_helper.rb に記載 %>
インデントがずれていますので，修正しましょう！

2021-04-17 23:22 UTC, hirokuni-k commented on app/views/layouts/application.html.erb
> +      <#% max_width メソッドは application_helper.rb に記載 %>
修正しましたが、できているでしょうか？

2021-04-17 23:59 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> +      <#% max_width メソッドは application_helper.rb に記載 %>
16行目のdivタグから全部1段ずれています！

2021-04-18 00:25 UTC, hirokuni-k commented on app/views/layouts/application.html.erb
> +      <#% max_width メソッドは application_helper.rb に記載 %>
これでどうでしょうか？

2021-04-18 22:23 UTC, T-Tsujii requested changes

2021-04-18 22:23 UTC, T-Tsujii commented on app/assets/stylesheets/application.css
> - */
こちらコメントではありませんので消してはいけません！

stylesheets内のCSSファイルを全て読み込むための設定です。

2021-04-19 02:41 UTC, T-Tsujii approved these changes
LGTMです！

2021-04-19 02:44 UTC, merged